LANG_PACK = {
    "繁體中文": {
        "model_select": "⚡️ 選擇回答模型",
        "model_setting": "模型設定",
        "user_and_topic": "🧑‍💻 用戶與主題",
        "user_label": "用戶",
        "add_user": "➕ 新增用戶",
        "add_user_btn": "確認新增用戶",
        "user_input": "輸入新用戶ID",
        "topic_label": "主題",
        "topic_select": "選擇主題",
        "topic_input": "輸入新主題名稱",
        "confirm_add_topic": "確認新增主題",
        "add_topic": "➕ 新增主題",
        "add_topic_btn": "確認新增主題",
        "topic_exists": "⚠️ 主題已存在",
        "upload_pdf": "📁 上傳財報 PDF",
        "company_name": "請輸入公司名稱",
        "pdf_upload_tip": "公司名稱不得為空，且不得只包含符號或 emoji。",
        "select_company": "📊 請選擇公司",
        "language_select": "🌐 語言選擇",
        "tab1": "💬 AI 問答",
        "tab2": "🧠 財報摘要",
        "tab3": "📊 財報圖表",
        "chat_title": "💬 財報 AI 聊天室",
        "chat_input": "請輸入您的問題或 /分析 指令 ...",
        "chat_example": "請輸入您的問題（中英文皆可），例如：\n- 台積電 2024 年第一季的營業收入是多少？\n- What is TSMC's Q1 2024 revenue?\n- /分析 預期未來折舊費用將上升",
        "clear_chat": "清除聊天記錄",
        "delete_user": "🗑️ 刪除用戶",
        "delete_topic": "🗑️ 刪除主題",
        "ai_reply_title": "🟧 **財報 AI 助理回覆**",
        "key_data_card": "📌 **關鍵數據卡**",
        "company": "公司",
        "query": "查詢",
        "revenue": "營業收入",
        "yoy_growth": "年增率",
        "ai_bullets": "🔎 **AI 條列重點**",
        "ai_bullet1": "AI 相關應用需求推升營收。",
        "ai_bullet2": "市場展望持續樂觀。",
        "no_data": "查無明確資料，建議檢查 PDF 內容。",
        "news_sources": "📑 **相關新聞／資料來源**",
        "no_news": "（無相關新聞）",
        "also_ask": "💬 **你還可以查詢**\n- 近五年營收趨勢圖\n- 同業營收（聯發科/鴻海/聯電）比較\n- 2024 Q1 淨利或 EPS",
        "ai_footer": "<sub>AI 財報助理自動整理．如需更多協助請繼續輸入問題！</sub>",
        # Sidebar & 功能提示/警告
        "warn_user_del": "⚠️ 此操作不可復原，請再次點擊下方按鈕確認！",
        "warn_topic_del": "⚠️ 此操作不可復原，請再次點擊下方按鈕確認！",
        "confirm_del": "⚡️ 確認永久刪除",
        "warn_topic_not_found": "主題檔案不存在",
        "warn_user_del_fail": "刪除用戶失敗：",
        "warn_topic_del_fail": "刪除主題失敗：",
        "switch_topic": "切換主題",
        "switch_topic_succ": "切換到用戶 [{user_id}] 主題 [{topic}]",
        "warn_no_company": "請先選擇公司",
        "upload_pdf_spinner": "建構向量資料庫中...（請勿重新整理或操作，預計 10-30 秒）",
        "upload_pdf_done": "✅ {company} 資料庫建立完成！",
        "upload_pdf_fail": "❌ 資料庫建立失敗：\n{err}",
        "upload_pdf_fail2": "❌ 建庫執行失敗：{err}",
        "adv_title": "📌 進階功能",
        "adv_log_search": "🔎 **聊天紀錄搜尋**",
        "adv_log_input": "輸入關鍵字搜尋本主題紀錄",
        "adv_log_count": "共找到 {num} 筆：",
        "adv_log_caption": "目前只搜尋本主題，可自行改寫支援所有主題",
        "sidebar_hint": """💡 使用建議：
- 先上傳公司財報 PDF，自動建立資料庫
- 可切換公司/語言，自由查詢
- 可分主題管理對話與歷史查詢
- 提問後可用 /分析 進行情緒預測
- 回覆內容更貼近 AI 口吻，自然簡明
""",
        # tab2 (摘要/AI summary)
        "tab2_title": "AI摘要＋情緒分析",   # 中文
        "tab2_markdown": "請貼上財報段落、新聞、管理層評論，AI自動幫你摘要經營重點並判斷情緒：", 
        "tab2_input_placeholder": "輸入財報或說明內容",
        "tab2_analyze_btn2": "AI 摘要與情緒判斷",
        "tab2_enter_content": "請輸入內容",
        "tab2_key_summary": "📝 摘要重點",
        "tab2_sentiment": "🏷️ 經營情緒：",
        # 既有 tab2 按鈕/快取/AI 指令等
        "tab2_clear_cache": "🗑️ 清除摘要快取",
        "tab2_cache_cleared": "已清除摘要快取！請重新產生摘要",
        "tab2_no_cache": "沒有可清除的摘要快取。",
        "tab2_btn": "產生財報AI摘要",
        "tab2_info_cached": "⚡️ 已讀取快取摘要，下次有新PDF再點一次重產即可",
        "tab2_spinner": "AI正在解析摘要...",
        "tab2_points_query": "請分點列出本期財報：1.營業收入/年增率 2.淨利/EPS 3.成長動能 4.展望。無資料可略過。",
        "tab2_points_none": "(查無可摘要內容)",
        "tab2_ai_query": "用AI助理的語氣，總結這份財報亮點與風險，並用一小段話解讀經營狀況，最後標註一個情緒標籤（樂觀/保守/中性）",
        "tab2_insufficient": "PDF 資料不足，已自動補充網路摘要",
        "tab2_web_note": "🌐 **網路自動補充摘要**",
        "tab2_suggestion": """💬 **你還可以查詢：**
- 近五年營收、EPS、毛利率趨勢
- 主要同業比較（聯發科/鴻海/聯電等）
- 產業未來展望與風險
""",
        "tab2_summary_title": "本期財報AI摘要",
        "tab2_summary_keydata": "數據重點",
        "tab2_summary_ai": "AI助理解讀",
        "tab2_summary_source": "資料來源：PDF向量庫/網路彙整，自動AI生成",
        "tab2_textarea": "自訂分析文字（可貼上財報段落）",
        "tab2_analyze_btn": "分析上述內容",
        "tab2_no_text": "請輸入要分析的內容",
        "tab2_spinner_analyze": "AI 分析中...",
        "tab2_result": "AI 分析結果：{result}",
        "tab2_result_none": "❌ 無法取得分析結果",
        "tab2_result_error": "❌ 分析過程發生錯誤：{err}",
        # tab3 (圖表/chart)
        "tab3": "📊 財報圖表",
        "tab3_title": "可產生單公司各財報指標趨勢圖，也可多公司同時比較。",
        "tab3_single": "單公司財報圖表",
        "tab3_indicator": "財報指標",
        "tab3_year": "選擇顯示年度區間",
        "tab3_chart_btn": "產生圖表分析",
        "tab3_spinner": "正在從網路自動抓取財報資料並製作圖表...",
        "tab3_no_data": "❌ 未能擷取到有效的圖表資料。你可以考慮手動上傳財報PDF，自動補全資料。",
        "tab3_hint_pdf": "👉 **查無網路資料？上傳官方財報 PDF 自動解析！**",
        # 多公司比較（全新欄位與舊欄位完整）
        "tab3_multi_title": "多公司財報圖表比較",
        "tab3_multi_company": "選擇公司（可複選）",
        "tab3_multi_indicator": "比較指標",
        "tab3_chart_size": "圖表大小",
        "tab3_multi_no_company": "請至少選擇一家公司進行比較",
        "tab3_multi_spinner": "正在查詢多家公司資料...",
        "tab3_multi_btn": "比較趨勢",
        "tab3_multi_no_data": "❌ 查無多家公司比較資料",
        "tab3_multi_chart_title": "多公司{indicator}歷年比較",
        "tab3_multi_chart_source": "資料來源：自動查詢；查詢時間：{time}",
        # 舊版相容
        "tab3_compare": "比較指標",
        "tab3_multi_select": "請選擇公司（可多選）",
        "tab3_multi": "多公司營收趨勢比較",
        "tab3_chart_title": "多公司歷年{indicator}比較",
        "tab3_chart_source": "資料來源：Google Serper API（自動網路擷取）；查詢時間：{time}",
    },

    "English": {
        "model_select": "⚡️ Model Selection",
        "model_setting": "Model Setting",
        "user_and_topic": "🧑‍💻 User & Topic",
        "user_label": "User",
        "add_user": "➕ Add User",
        "add_user_btn": "Confirm Add User",
        "user_input": "Enter new user ID",
        "topic_label": "Topic",
        "topic_select": "Select Topic",
        "topic_input": "Enter new topic name",
        "confirm_add_topic": "Confirm Add Topic",
        "add_topic": "➕ Add Topic",
        "add_topic_btn": "Confirm Add Topic",
        "topic_exists": "⚠️ Topic already exists",
        "upload_pdf": "📁 Upload Financial PDF",
        "company_name": "Enter company name",
        "pdf_upload_tip": "Company name cannot be empty, or contain only symbols/emoji.",
        "select_company": "📊 Select Company",
        "language_select": "🌐 Language",
        "tab1": "💬 AI Q&A",
        "tab2": "🧠 Report Summary",
        "tab3": "📊 Chart Analysis",
        "chat_title": "💬 Financial AI Chat Room",
        "chat_input": "Enter your question or /analyze ...",
        "chat_example": "Ask your question (either language), e.g.:\n- What is TSMC's Q1 2024 revenue?\n- 台積電 2024 年第一季的營業收入是多少？\n- /analyze Depreciation expense is expected to rise",
        "clear_chat": "Clear Chat History",
        "delete_user": "🗑️ Delete User",
        "delete_topic": "🗑️ Delete Topic",
        "ai_reply_title": "🟧 **Financial AI Assistant Answer**",
        "key_data_card": "📌 **Key Data Card**",
        "company": "Company",
        "query": "Query",
        "revenue": "Revenue",
        "yoy_growth": "YoY Growth",
        "ai_bullets": "🔎 **AI Bullet Points**",
        "ai_bullet1": "AI-driven applications are boosting revenue.",
        "ai_bullet2": "Market outlook remains positive.",
        "no_data": "No clear data found. Please check the PDF content.",
        "news_sources": "📑 **News / Sources**",
        "no_news": "(No related news)",
        "also_ask": "💬 **You can also ask**\n- Revenue trends for last 5 years\n- Peer comparison (MediaTek/Foxconn/UMC)\n- 2024 Q1 net profit or EPS",
        "ai_footer": "<sub>Financial AI assistant auto summary. Continue your questions for more!</sub>",
        # Sidebar & warning
        "warn_user_del": "⚠️ This cannot be undone, click again to confirm!",
        "warn_topic_del": "⚠️ This cannot be undone, click again to confirm!",
        "confirm_del": "⚡️ Confirm Permanent Delete",
        "warn_topic_not_found": "Topic file not found",
        "warn_user_del_fail": "Delete user failed: ",
        "warn_topic_del_fail": "Delete topic failed: ",
        "switch_topic": "Switch Topic",
        "switch_topic_succ": "Switched to user [{user_id}], topic [{topic}]",
        "warn_no_company": "Please select a company first",
        "upload_pdf_spinner": "Building vector DB... Please wait.",
        "upload_pdf_done": "✅ {company} database created!",
        "upload_pdf_fail": "❌ DB build failed:\n{err}",
        "upload_pdf_fail2": "❌ Build process failed: {err}",
        "adv_title": "📌 Advanced",
        "adv_log_search": "🔎 **Chat Log Search**",
        "adv_log_input": "Search keyword in current topic history",
        "adv_log_count": "Found {num} record(s):",
        "adv_log_caption": "Currently searches only this topic. You can modify to support all topics.",
        "sidebar_hint": """💡 Suggestions:
- Upload company financial PDF first to build the database
- Switch company/language freely for queries
- Manage topics and chat history
- Use /analyze for sentiment analysis
- Answers are now more conversational and AI-like
""",
        # tab2 (summary/AI)
        "tab2_title": "AI Summary & Sentiment Analysis",
        "tab2_markdown": "Paste any financial paragraph, news, or management comment. AI will summarize key points and judge sentiment:",
        "tab2_input_placeholder": "Enter financial/statement text",
        "tab2_analyze_btn2": "AI Summary & Sentiment",
        "tab2_enter_content": "Please enter some content",
        "tab2_key_summary": "📝 Key Summary",
        "tab2_sentiment": "🏷️ Sentiment: ",
        # existing tab2
        "tab2_clear_cache": "🗑️ Clear summary cache",
        "tab2_cache_cleared": "Summary cache cleared! Please re-generate.",
        "tab2_no_cache": "No summary cache found.",
        "tab2_btn": "Generate AI Summary",
        "tab2_info_cached": "⚡️ Loaded cached summary, re-run only for new PDF.",
        "tab2_spinner": "AI analyzing summary...",
        "tab2_points_query": "List: 1. Revenue/growth rate 2. Net profit/EPS 3. Growth drivers 4. Outlook. Skip if no data.",
        "tab2_points_none": "(No summary available)",
        "tab2_ai_query": "In AI assistant tone, summarize highlights/risks in one paragraph, add a sentiment label (Optimistic/Conservative/Neutral)",
        "tab2_insufficient": "PDF data insufficient, auto supplementing web summary.",
        "tab2_web_note": "🌐 **Web supplement**",
        "tab2_suggestion": """💬 **You can also ask:**
- Revenue/EPS/gross margin trends (5 years)
- Main peer comparison (MediaTek/Foxconn/UMC etc.)
- Industry outlook and risks
""",
        "tab2_summary_title": "AI Summary for This Period",
        "tab2_summary_keydata": "Key Data",
        "tab2_summary_ai": "AI Insights",
        "tab2_summary_source": "Source: PDF vector DB/Web, AI generated",
        "tab2_textarea": "Custom analysis text (paste report section)",
        "tab2_analyze_btn": "Analyze above content",
        "tab2_no_text": "Please enter content to analyze.",
        "tab2_spinner_analyze": "AI analyzing...",
        "tab2_result": "AI Analysis Result: {result}",
        "tab2_result_none": "❌ No result",
        "tab2_result_error": "❌ Error occurred: {err}",
        # tab3 (chart)
        "tab3": "📊 Chart Analysis",
        "tab3_title": "Generate single or multi-company trend charts for financial indicators.",
        "tab3_single": "Single Company Chart",
        "tab3_indicator": "Indicator",
        "tab3_year": "Select year range",
        "tab3_chart_btn": "Generate Chart",
        "tab3_spinner": "Retrieving data and generating chart...",
        "tab3_no_data": "❌ No valid chart data found. Consider uploading an official PDF for auto-fill.",
        "tab3_hint_pdf": "👉 **No web data? Upload the official PDF for auto analysis!**",
        "tab3_multi_title": "Multi-company Chart Comparison",
        "tab3_multi_company": "Select Companies (multiple allowed)",
        "tab3_multi_indicator": "Compare Indicator",
        "tab3_multi_no_company": "Please select at least one company to compare",
        "tab3_chart_size": "Chart Size",
        "tab3_multi_spinner": "Retrieving multi-company data...",
        "tab3_multi_btn": "Compare Trends",
        "tab3_multi_no_data": "❌ No multi-company comparison data found",
        "tab3_multi_chart_title": "Multi-company {indicator} Comparison (Yearly)",
        "tab3_multi_chart_source": "Source: Auto query; Query time: {time}",
        "tab3_compare": "Compare Indicator",
        "tab3_multi_select": "Select Companies (multiple allowed)",
        "tab3_multi": "Multi-company Revenue Comparison",
        "tab3_chart_title": "{indicator} Comparison (Multi-company, Yearly)",
        "tab3_chart_source": "Source: Google Serper API (web); Query time: {time}",
    }
}
